version: '3.4'

services:

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=Dachi123;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=654123
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - catalogdb
    volumes:
      - ~/.aspnet/https:/https:ro
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;Username=postgres;Password=Dachi123;
      - ConnectionStrings__Redis=distributedcache:6379
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=654123
    ports:
      - "6001:8080"
      - "6061:8081"
    depends_on:
      - basketdb
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=654123
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  catalogdb:
    container_name: catalogdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: CatalogDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_data:/var/lib/postgresql/data

  basketdb:
    container_name: basketdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: BasketDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5433:5432"
    volumes:
      - basketdb_data:/var/lib/postgresql/data

  distributedcache:
    image: redis
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

volumes:
  catalogdb_data:
  basketdb_data: